"""add startup models

Revision ID: bcbb4a818b9d
Revises: 6d421afaf99a
Create Date: 2025-09-14 23:58:44.128515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcbb4a818b9d'
down_revision: Union[str, None] = '6d421afaf99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inference_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('inference_json', sa.JSON(), nullable=False),
    sa.Column('processed_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('audit_user_ip', sa.String(length=16), nullable=False),
    sa.Column('audit_created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('audit_updated_on', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('audit_user_login', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inference_history_id'), 'inference_history', ['id'], unique=False)
    op.create_index(op.f('ix_inference_history_startup_id'), 'inference_history', ['startup_id'], unique=False)
    op.create_table('startups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('founders', sa.JSON(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('health_focus', sa.String(), nullable=False),
    sa.Column('confidence_traces', sa.JSON(), nullable=False),
    sa.Column('audit_user_ip', sa.String(length=16), nullable=False),
    sa.Column('audit_created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('audit_updated_on', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('audit_user_login', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startups_id'), 'startups', ['id'], unique=False)
    op.create_index(op.f('ix_startups_name'), 'startups', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_startups_name'), table_name='startups')
    op.drop_index(op.f('ix_startups_id'), table_name='startups')
    op.drop_table('startups')
    op.drop_index(op.f('ix_inference_history_startup_id'), table_name='inference_history')
    op.drop_index(op.f('ix_inference_history_id'), table_name='inference_history')
    op.drop_table('inference_history')
    # ### end Alembic commands ###
